#!/usr/bin/env python3
# -*- coding: utf-8 -*-

'''
@date: 2021-04
@author: nboutin
'''
start = '2021-01'
entities = {
    'lot': {'lot1': {'lot_type': {start: 'Commerce'},
                     'surface': {start: 64.85},
                     'loyer_nu': {'2021': 550 * 12},
                     'travaux': {start: 8000},  # rafraichissement
                     'anah_subvention_taux': {start: 0},
                     'anah_subvention_plafond': {start: 0},
                     'deficit_foncier_eligible': {start: 8000},
                     'charge_provision': {start: 40},
                     'copropriete': {start: 0},
                     'taxe_fonciere': {start: 0},
                     'pno': {'2021': 100},
                     'gestion_agence_taux': {start: 0},
                     'travaux_provision': {start: 0},
                     'vacance_locative_taux': {start: 0},
                     },
            'lot2': {'lot_type': {start: 'T3'},
                     'surface': {start: 62},
                     'surface_annexe': {start: 16},
                     'loyer_nu': {'2021': 476 * 12},
                     'travaux': {start: 33250},
                     'anah_subvention_taux': {start: .25},
                     'anah_subvention_plafond': {start: 0},
                     'anah_subvention_base': {start: 750},
                     'prime_habiter_mieux': {start: 2000},
                     'deficit_foncier_eligible': {start: 33250},  # subvention soustraite apres
                     'charge_provision': {start: 40},
                     'copropriete': {start: 0},
                     'taxe_fonciere': {start: 0},
                     'pno': {'2021': 100},
                     'gestion_agence_taux': {start: 0},
                     'travaux_provision': {start: 0},
                     'vacance_locative_taux': {start: 0},
                     },
            'lot3': {'lot_type': {start: 'T3'},
                     'surface': {start: 62},
                     'loyer_nu': {'2021': 476 * 12},
                     'travaux': {start: 68250},
                     'anah_subvention_taux': {start: .35},
                     'anah_subvention_plafond': {start: 0},
                     'anah_subvention_base': {start: 750},
                     'prime_habiter_mieux': {start: 2000},
                     'deficit_foncier_eligible': {start: 68250},  # subvention soustraite apres
                     'charge_provision': {start: 40},
                     'copropriete': {start: 0},
                     'taxe_fonciere': {start: 0},
                     'pno': {'2021': 100},
                     'gestion_agence_taux': {start: 0},
                     'travaux_provision': {start: 0},
                     'vacance_locative_taux': {start: 0},
                     },
            'commun': {'lot_type': {start: 'Commun'},
                       # Toiture, partie commune, soliha, jch, jch
                       'travaux': {start: [29000, 5000, 1300, 150, 450]},
                       'anah_subvention_taux': {start: 0},
                       'anah_subvention_plafond': {start: 0},
                       'deficit_foncier_eligible': {start: 0},
                       },
            },
    'bien_immo': {'bi1': {'lot': ['lot1', 'lot2', 'lot3', 'commun'],
                          'prix_achat': {start: 115000},
                          'taux_notaire': {start: 0.08},
                          'taux_agence': {start: 0.07},
                          'apport': {start: 0},
                          }},
    'credit': {'c1': {'duree': {start: 20 * 12},
                      # 'financement':{start: all},
                      'taux_interet': {start: 0.0115},
                      'taux_assurance': {start: 0.0035},
                      'frais_dossier': {start: 300},
                      'frais_garantie': {start: 0},
                      }},
    'fiscalite': {'f1': {'regime': {start: 'location_vide_reel'},
                         'openfisca': {'individus': {'Ni': {},
                                                     'Au': {},
                                                     'Ly': {}},
                                       'foyers_fiscaux': {'f1': {'declarants': ['Ni', 'Au'],
                                                                 'personnes_a_charge': ['Ly']}},
                                       'menages': {'roles': {'personne_de_reference': 'Ni',
                                                             'conjoint': 'Au',
                                                             'enfants': 'Ly'}},
                                       'familles': {'roles': {'parents': ['Ni', 'Au'],
                                                              'enfants': ['Ly']}}, }},
                  'f2': {'regime': {start: 'sci_is'}},
                  },
    'analyse': {'a1': {'bien_immo': 'bi1',
                       'credit': 'c1',
                       'fiscalite': 'f1',
                       },
                }
}
